### ISSUE TITLE
Remove unused css file

### ISSUE THREAD

**Issue by benrosen** [benrosen/phaser-react-tools#3]
When this project was bootstrapped, [create-react-library][0] created [styles.module.css][1] which is not being used, and which is being built to `/dist/`. It should be removed to reduce package size.

[0]: https://www.npmjs.com/package/create-react-library 'create-react-library'
[1]: https://github.com/benrosen/phaser-react-tools/blob/cf07306cc4e3ea5a280d135292c1d015971f794d/src/styles.module.css 'styles.module.css'

**Comment by JoseLRiano** [comment]
Hello, so you just want to remove the file that is located at src > styles.module.css?

**Comment by benrosen** [comment]
Yep. I'd like to make sure it also gets removed from the /dist/ folder when the project is built. Should happen automatically. I haven't set up the wiki yet so let me know if you need a hand getting everything running on your machine.

**Comment by benrosen** [comment]
#5
