### ISSUE TITLE
Add support for TypeScript

### ISSUE THREAD

**Issue by benrosen** [benrosen/phaser-react-tools#6]
Since this project is bootstrapped with [create-react-library][0], which itself is built on top of [create-react-app][1], it should be trivial to add support for TypeScript. I'm very open to community feedback on what "TypeScript support" should entail, so leave a comment if you have ideas/requests/comments/concerns/etc.

[0]: https://www.npmjs.com/package/create-react-library 'create-react-library'
[1]: https://github.com/facebook/create-react-app 'create-create-app'

**Comment by paulofaria** [comment]
Hello, I'd love to contribute with Typescript support. I don't have much experience with JS/TS, though. Do you have plans to add TS support soon? are you expecting contributions?
